app/ca/routes.py
import csv
import json
import os

from flask import 
    Blueprint, 
    render_template, 
    redirect, 
    url_for, 
    flash, 
    session

from helper_classes.heading import HeadingCA
from helper_classes.tariffrate import TariffRateCA
import app.ca.models

ca_bp = Blueprint('ca', __name__, url_prefix='/ca/', template_folder='templates')

@ca_bp.route('/<year>/heading/<tariff>')
def heading_lookup(year, tariff):

    if len(tariff) in [4, 6]:
        try:
            if session['year']:
                h = HeadingCA(tariff, session['year'])
            else:
                h = HeadingCA(tariff, year)
      
            return render_template('ca/heading-lookup.html', title=f"Heading {tariff}", year=year, h=h)
        except Exception as e:            
            flash(f"Invalid heading {tariff}, {e}")
    else:
        flash(f"Invalid tariff {tariff}")
    return redirect(url_for('main.index'))


@ca_bp.route('/<year>/tariff/<tariff>')
def tariff_lookup(year, tariff):

    if len(tariff) == 10:
        try:
            dev = ''
            if os.environ.get('FLASK_ENV') == 'development':
                dev = '/kras'
            if session['year']:
                t = TariffRateCA(tariff=tariff, year=session['year'])
            else:
                t = TariffRateCA(tariff=tariff, year=year)
            tt = None
            with open(f'/home{dev}/vector/tarifftank/app/data/ca/tarifftreatment.json', 'r') as f:
                tt = json.load(f)

            # SIMA
            sima_info = []
            with open(f'/home{dev}/vector/tarifftank/app/data/ca/sima_info.json', 'r') as f:
                sima = json.load(f)
                for row in sima:
                    if t.tariff in row['Tariff classification numbers']:
                        sima_info.append(row)
            print(sima_info)
            
            # PGA    

            return render_template('ca/tariff-lookup.html', title=t.tariff, t=t, tt=tt, sima_info=sima_info)
        except Exception as e:
            print(f"ERROR: {e}")
            flash(f"invalid 10-digit HS code - {tariff}, {e}")
    return redirect(url_for('main.index'))


@ca_bp.route('/<year>/chapter/<tariff>')
def chapter_lookup(year, tariff):
    chapter = tariff
    table = vars(app.ca.models)[f"CA{year}"]
    results = table.query.filter(table.tariff.like(f"{chapter}%"))
    headings = [HeadingCA(t) for t in sorted(set([i.tariff[:4] for i in results]))[:100]]

    return render_template('ca/chapter-lookup.html', headings=headings, chapter=chapter, title=f"Chapter - {chapter}")    


@ca_bp.route('/<year>/text-search/<tariff>')
def text_search(year, tariff):
    keyword = tariff
    if ''.join(keyword.split()).isalpha():
        table = vars(app.ca.models)[f"CA{year}"]
        results = table.query.filter(table.description.like(f"%{keyword}%"))
        headings = [HeadingCA(t, year) for t in sorted(set([i.tariff[:4] for i in results]))[:100]]

        return render_template('ca/text-search.html', headings=headings, keyword=keyword, title=f"Search - {keyword}")
    else:
        return "Error"


    return render_template('ca/index.html', title="Canada", year=year, tariff=tariff)
    

app/ca/templates/ca/chapter-lookup.html
{% extends "layout.html" %}
{% from "macros.html" import heading_accordion %}

{% block main %}
<div class="callout">
    <h1>Chapter:<small> "{{chapter}}"</small></h1>    
    <p>{{headings | length}} headings</p>
</div>

{% for heading in headings %}
{{heading_accordion(heading.gen_tariff_dict())}}

{% endfor %}
{% endblock %}

app/ca/templates/ca/heading-lookup.html
{% extends "layout.html" %}
{% from "macros.html" import heading_accordion, notes, bookview %}

{% block main %}

<div class="callout">
    <h1>{% if h.heading | length == 4 %}Heading {% else %}Sub-heading {% endif %}<small>{{h.heading | format_hs}}</small></h1>
</div>

<ul class="tabs" data-tabs id="example-tabs">
    <li class="tabs-title is-active"><a href="#panel4" aria-selected="true">Book View</a></li>
    <li class="tabs-title"><a data-tabs-target="panel1" href="#panel1" >Tree View</a></li>
    <li class="tabs-title"><a data-tabs-target="panel2" href="#panel2">Section Notes</a></li>
    <li class="tabs-title"><a data-tabs-target="panel3" href="#panel3">Chapter Notes</a></li>
</ul>

<div class="tabs-content" data-tabs-content="example-tabs">
    <div class="tabs-panel" id="panel1">
        <p>{{heading_accordion(h.gen_tariff_dict(), active=True)}}</p>
    </div>
    <div class="tabs-panel" id="panel2">
        <h3>Section {{h.section_notes.number}} - {{h.section_notes.title}}</h3>      

        <div class="grid-x grid-padding-x">
            <div class="cell small-12">
                {{notes(h.section_notes)}}     
            </div>
        </div>  
    </div>

    <div class="tabs-panel" id="panel3">
        <h3>Chapter {{h.chapter_notes.chapter}} - {{h.chapter_notes.title}}</h3>
        <div class="grid-x grid-padding-x">
            <div class="cell small-12 ">
                {{notes(h.chapter_notes)}}     
            </div>
        </div>
    </div>

    <div class="tabs-panel is-active" id="panel4">
        <h3>Book View {{h.heading | format_hs}}</h3>
        <div class="grid-x grid-padding-x">
            {#<div class="cell medium-2">
                <!-- <nav class="sticky-container" data-sticky-container>
                    <div class="sticky" data-sticky data-anchor="tariffMenu" data-sticky-on="large"> -->
                        <ul class="vertical menu" data-magellan>
                            {% for row in h.book_view_web() %}
                            {% if row.tariff %}
                            <li><a class="button primary hollow small" href="#{{row.tariff}}{% if row.ss %}{{row.ss}}{% endif %}">{{row.tariff | format_hs}}{% if row.ss %}.{{row.ss}}{% endif %}</a></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    <!-- </div>
                </nav> -->
            </div>#}
            <div class="cell small-12 medium-10 medium-offset-1">
                {{bookview(h.book_view_web())}}     
            </div>
            
        </div>     
    </div>
</div>

{% endblock %}

app/ca/templates/ca/index.html
{% extends "layout.html" %}


{% block main %}
<h1>Canada Blueprints</h1>
<p>This is a paragraph</p>
<p>Tryina look up {{tariff}} in {{year}}</p>

{% endblock %}

app/ca/templates/ca/tariff-lookup.html
{% extends "layout.html" %}
{% from "macros.html" import notes %}

{% block main %}

<div class="callout">
    <h1 class=>{{t.tariff | format_hs}} <small>&nbsp;{{t.year}} Canadian Tariff</small></h1>
</div>

<ul class="tabs" data-tabs id="example-tabs">
    <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Tariff Rates</a></li>
    <li class="tabs-title"><a data-tabs-target="panel2" href="#panel2">Section Notes</a></li>
    <li class="tabs-title"><a data-tabs-target="panel3" href="#panel3">Chapter Notes</a></li>
    {%- if t.pga %}
    <li class="tabs-title"><a data-tabs-target="panel4" href="#panel4">PGA</a></li>
    {% endif %}

    {# IF sima_info link is red #}
    <li class="tabs-title">        
        <a class="{% if sima_info %}red{% endif %}" data-tabs-target="panel5" href="#panel5">SIMA</a>
    </li>
</ul>

<div class="tabs-content" data-tabs-content="example-tabs">
    <div class="tabs-panel is-active" id="panel1">

        {% for hs, description in t.descriptions.items() %}
        {% if hs != "None" %}
        <div class="grid-x grid-padding-x">
            <div class="cell small-4 medium-3 large-2 text-right">
                <p>
                    {% if hs | length == 4 %}
                    <a href="{{url_for('ca.heading_lookup', year=t.year, tariff=hs)}}">{{hs | format_hs}}</a>
                    {% else %}
                    {{hs | format_hs}}
                    {% endif %}
                </p>
            </div>
            <div class="cell small-8, medium-8 large-8">
                <p class="text-justify">{{description}}</p>
            </div>
        </div>
        {% endif %}        
        {% endfor %}
        <div class="grid-x grid-margin-x small-margin-collapse">
            <div class="cell small-12 medium-8 large-8 large-offset-2 medium-offset-2">
                <table>
                    <thead>
                        <th>FTA</th>
                        <th>Rate</th>
                        <th>UOM</th>
                    </thead>
                    <tbody>
                        {% for fta, rate in t.rates.items() %}
                        <tr>
                            {# FTA #}
                            <td width="200"><span data-tooltip class="top" tabindex="2" title="{{tt[fta]}}">{{fta | upper}}</span></td>
                            
                            {# Rate format #}
                            {% if rate != "Free" %}
                            <td width="400" style="color: black;">{{rate}}</td>
                            {% else %}
                            <td width="400" style="opacity: 0.5;">{{rate}}</td>
                            {% endif %}
                            
                            {# UOM #}
                            <td width="100">{{t.uom}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
    <div class="tabs-panel" id="panel2">
        <h3>Section {{t.section_notes.number}} - {{t.section_notes.title}}</h3>
      
        {{notes(t.section_notes)}}

    </div>
    <div class="tabs-panel" id="panel3">

        <h3>Chapter {{t.chapter_notes.chapter}} - {{t.chapter_notes.title}}</h3>
        
        {{notes(t.chapter_notes)}}
     
    </div>
    <div class="tabs-panel" id="panel4">
        <div class="grid-x grid-margin-x small-margin-collapse">
            <div class="cell small-12 medium-10 large-11 large-offset-0 medium-offset-1">
                <table>
                    <thead>
                        <th>PGA</th>
                        <th>Program</th>
                        <th>Matching Criteria</th>
                        <th>Pga Link</th>
                    </thead>
                    <tbody>
                        {% if t.pgas %}
                        {% for pga in t.pgas %}
                        <tr>
                            <td width="400">{{pga.name}} ({{pga.code}})</td>
                            <td widht="400">{{pga.subpganame}}</td>
                            <td width="100"><a href="{{pga.swilink}}">{{pga.code}}</a></td>
                            <td widht="100"><a href="{{pga.pgalink}}">{{pga.code}} Home</a></td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="tabs-panel" id="panel5">
        <div class="grid-x grid-margin-x small-margin-collapse">
            <div class="cell small-12">
                {% if sima_info %}
                <table>
                    <thead>
                        <th>Case</th>
                        <th>Case Type</th>
                        <th>Classification Numbers</th>
                    </thead>
                    <tbody>
                        {% for sima in sima_info %}
                        <tr>
                            <td width="200"><a href="https://www.cbsa-asfc.gc.ca{{sima['link']}}">{{sima.Case}}</a></td>
                            <td width="300">{{sima['Case type']}}</td>
                            <td>{{sima['Tariff classification numbers'] | format_hslist | join(' , ')}}</td>                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="text-left">This tariff is not subject to SIMA duties</div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/ca/templates/ca/text-search.html
{% extends "layout.html" %}
{% from "macros.html" import heading_accordion %}

{% block main %}
<div class="callout">
    <h1>Search:<small> "{{keyword}}"</small></h1>
    <p>Found {{headings | length}} results</p>
</div>

{% for heading in headings %}
{{heading_accordion(heading.gen_tariff_dict()) | embolden(keyword) }}
{% endfor %}
{% endblock %}