app/main/routes.py
import json
import string

from flask import 
    Blueprint, 
    render_template, 
    request, 
    redirect, 
    url_for, 
    session, 
    flash, 
    make_response, 
    jsonify
    
from .forms import ContactForm, SearchForm
from .models import ContactMessage
from app.factory import db
from helper_classes.heading import HeadingCA
from helper_classes.tariffrate import TariffRateCA



main_bp = Blueprint('main', __name__, url_prefix='/', template_folder='templates', static_folder='static')


@main_bp.route('/robots.txt')
def robots():
    return main_bp.send_static_file('robots.txt')

# ----------ROOT-------------
@main_bp.route('/') 
def index():
    form = SearchForm()


    return render_template('main/index.html', title="TariffTank Search", form=form)


# ----------ABOUT-------------
@main_bp.route('/about') 
def about():
    return render_template('main/about.html', title="About TariffTank(c)")


# ----------CONTACT-------------
@main_bp.route('/contact', methods=['GET', 'POST'])
def contact():

    form = ContactForm()

    if form.validate_on_submit():
        email = form.email.data
        subject = form.subject.data
        message = form.message.data

        entry = ContactMessage(email=email, subject=subject, message=message, remote_address=request.remote_addr)
        db.session.add(entry)
        db.session.commit()


        print(f"Email: {email}")
        print(f"Subject: {subject}")
        print(f"Message: {message}")
        flash("The form has been submitted. Thank you!")
        return redirect(url_for('main.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"Error in the {getattr(form, field).label.text}'s field - {error}'")
        


    return render_template('main/contact.html', title='Contact', form=form)


# ----------SEARCH-------------
@main_bp.route('/search', methods=['GET', 'POST']) 
def search():
    form = SearchForm()

    
    if request.method == 'POST':
        session['year'] = request.form.get('year') or session['year']
        session['region'] = request.form.get('region') or session['region']
        keyword = request.form.get('keyword').replace('.', '')
        print(f"KEYWORD: {keyword}")

        # no input
        if not keyword:
            return redirect(url_for('main.index'))

        if len(keyword) == 2 and keyword.isdigit():
            page = 'chapter_lookup'
        elif len(keyword) in [4, 6] and keyword.isdigit():
            page = 'heading_lookup'
        elif len(keyword) == 10 and keyword.isdigit():
            page = 'tariff_lookup'
        elif ''.join(keyword.split()).isalpha():
            if len(keyword) < 4:
                flash("keyword must be minimum 4 characters")
                return redirect(url_for('main.index'))
            page = 'text_search'
        else:
            flash("Invalid input")
            return redirect(url_for('main.index'))
        

        if session['region'] == 'ca':
            return redirect(url_for(f'ca.{page}', year=session['year'], tariff=keyword))

        # elif session['region'] == 'us':
        #     return redirect(url_for(f'us.{page}', year=session['year'], tariff=keyword))

        # elif session['region'] == 'eu':
        #     return redirect(url_for(f'eu.{page}', year=session['year'], tariff=keyword))

    else:
        session['year'] = '2020'
        session['region'] = 'ca'
    print(session['year'])
    print(session['region'])
    
    return redirect(url_for('main.index'))


# @main_bp.errorhandler(429)
# def ratelimit_handler(e):
#     return render_template('main/rate-limit.html', title="RATE LIMIT EXCEEDED")


    

app/templates/includes/_footer.html
        <div class="grid-y grid-padding-y ">
            
            <div class="cell small-5">
                <div class="grid-x grid-padding-x">
                    <div class="cell small-4">
                        <p>.</p>
                    </div>
                </div>
            </div>

            <div><p>&nbsp;&copy; Copyright 2020 <a href="#">TariffTank</a>. <span class="text-right"> TariffTank.com is powered by <a href="https://www.google.com/search?q=trash+panda&rlz=1C1CHBF_enCA703CA703&sxsrf=ACYBGNT_QR2Q0DprqHo8GuzUeufEYiLzjg:1578600758566&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiJhNOLqvfmAhUNTN8KHTcCDP8Q_AUoAXoECBMQAw&biw=1536&bih=700" target="_blank">trash pandas</a></span></p>
            </div>
        </div>
        

app/templates/includes/_navbar.html
    <div data-sticky-container>
        <div data-sticky data-options="marginTop:0;" data-sticky-on="small">
            <div class="title-bar sticky" data-responsive-toggle="responsive-menu" data-hide-for="medium">
                <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
                <div class="title-bar-title">Menu</div>
            </div>

            <div class="top-bar topbar-center-logo" id="responsive-menu" data-responsive-toggle="responsive-menu" data-hide-for="medium" style="width:100%;">
                <div class="top-bar-left">
                    <ul class="menu vertical medium-horizontal">
                        {#- LOGO #}              
                        <li>
                            <a class="clear button" href="{{url_for('main.index')}}"><img style="max-height: 35px;" src="{{url_for('static', filename='img/logo_156_35.png')}}" alt="Logo"></a>
                        </li>                    
                    </ul>
                </div>
                {#<div id="navSearchBar" class="top-bar-center">
                    <form class="search-form" action="{{url_for('main.search')}}" method="post">
                        <div class="grid-x">
                            <div class="cell small-6">
                                <input class="float-right" name="keyword" type="search" placeholder="Quick Search">
                            </div>
                            <div class="cell auto">
                                <input type="submit" class="button" value="Go">
                            </div>
                        </div>
                    </form>
                </div>#}
                <div class="top-bar-right">
                    <ul class="menu button-group" data-dropdown-menu>
                        {# MENU ITEMS #}
                        <li>
                            <div id="navSearchBar" class="top-bar-center">
                                <form class="search-form" action="{{url_for('main.search')}}" method="post">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                    <div class="grid-x">
                                        <div class="cell small-6">
                                            <input name="keyword" type="search" placeholder="Quick Search">
                                        </div>
                                        <div class="cell auto">
                                            <input type="submit" class="button" value="Go">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <li><a class="clear button" href="{{url_for('main.about')}}">About</a></li>
                        <li><a class="clear button" href="#" disabled>Dev-Blog</a></li>            
                        <li><a class="clear button" href="{{url_for('main.contact')}}">Contact</a></li>            
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {#
    <!-- mobile nav bar -->
    <div class="title-bar topbar-center-logo-mobile" data-responsive-toggle="topbar-center-logo" data-hide-for="medium">
        <div class="title-bar-left">
        <div class="title-bar-title"><img src="https://placehold.it/100x39" alt="" /></div>
        </div>
        <div class="title-bar-right">
        <button class="menu-icon" type="button" data-toggle="topbar-center-logo"></button>
        </div>
    </div>
    <!-- /mobile nav bar -->
    
    <!-- medium and larger nav bar -->
    <div class="top-bar topbar-center-logo" id="topbar-center-logo">
        <div class="top-bar-left">
        <ul class="menu vertical medium-horizontal">
            <li><a href="#"><img src="{{url_for('static', filename='img/logo_156_35.png')}}" alt="" /></a></li>
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
            <li><a href="#">Three</a></li>
        </ul>
        </div>
        <div class="top-bar-center">
        <a href="#"><img src="{{url_for('static', filename='img/logo_156_35.png')}}" alt="" /></a>
        </div>
        <div class="top-bar-right">
        <ul class="menu vertical medium-horizontal">
            <li><a href="#">Four</a></li>
            <li><a href="#">Five</a></li>
            <li><a href="#">Six</a></li>
        </ul>
        </div>
    </div>
    <!-- /medium and larger nav bar -->
    #}
        
        