app/ca/routes.py
import csv
import json
import os

from flask import 
    Blueprint, 
    render_template, 
    redirect, 
    url_for, 
    flash, 
    session

from helper_classes.heading import HeadingCA
from helper_classes.tariffrate import TariffRateCA
import app.ca.models

ca_bp = Blueprint('ca', __name__, url_prefix='/ca/', template_folder='templates')

@ca_bp.route('/<year>/heading/<tariff>')
def heading_lookup(year, tariff):

    if len(tariff) in [4, 6]:
        try:
            if session['year']:
                h = HeadingCA(tariff, session['year'])
            else:
                h = HeadingCA(tariff, year)
      
            return render_template('ca/heading-lookup.html', title=f"Heading {tariff}", year=year, h=h)
        except Exception as e:            
            flash(f"Invalid heading {tariff}, {e}")
    else:
        flash(f"Invalid tariff {tariff}")
    return redirect(url_for('main.index'))


@ca_bp.route('/<year>/tariff/<tariff>')
def tariff_lookup(year, tariff):

    if len(tariff) == 10:
        try:
            dev = ''
            if os.environ.get('FLASK_ENV') == 'development':
                dev = '/kras'
            if session['year']:
                t = TariffRateCA(tariff=tariff, year=session['year'])
            else:
                t = TariffRateCA(tariff=tariff, year=year)
            tt = None
            with open(f'/home{dev}/vector/tarifftank/app/data/ca/tarifftreatment.json', 'r') as f:
                tt = json.load(f)

            # SIMA
            sima_info = []
            with open(f'/home{dev}/vector/tarifftank/app/data/ca/sima_info.json', 'r') as f:
                sima = json.load(f)
                for row in sima:
                    if t.tariff in row['Tariff classification numbers']:
                        sima_info.append(row)
            print(sima_info)
            
            # PGA    

            return render_template('ca/tariff-lookup.html', title=t.tariff, t=t, tt=tt, sima_info=sima_info)
        except Exception as e:
            print(f"ERROR: {e}")
            flash(f"invalid 10-digit HS code - {tariff}, {e}")
    return redirect(url_for('main.index'))


@ca_bp.route('/<year>/chapter/<tariff>')
def chapter_lookup(year, tariff):
    chapter = tariff
    table = vars(app.ca.models)[f"CA{year}"]
    results = table.query.filter(table.tariff.like(f"{chapter}%"))
    headings = [HeadingCA(t) for t in sorted(set([i.tariff[:4] for i in results]))[:100]]

    return render_template('ca/chapter-lookup.html', headings=headings, chapter=chapter, title=f"Chapter - {chapter}")    


@ca_bp.route('/<year>/text-search/<tariff>')
def text_search(year, tariff):
    keyword = tariff
    if ''.join(keyword.split()).isalpha():
        table = vars(app.ca.models)[f"CA{year}"]
        results = table.query.filter(table.description.like(f"%{keyword}%"))
        headings = [HeadingCA(t, year) for t in sorted(set([i.tariff[:4] for i in results]))[:100]]

        return render_template('ca/text-search.html', headings=headings, keyword=keyword, title=f"Search - {keyword}")
    else:
        return "Error"


    return render_template('ca/index.html', title="Canada", year=year, tariff=tariff)
    

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Google Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Foundation -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/foundation.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

    <title>{{title | format_hs}}</title>
    
</head>
<body>
    {% from "macros.html" import navbar %}
    <header>
    {{ navbar() }}    
    </header>

    <main>
    {% block main %}{% endblock %}
    </main>        

    <footer class="footer">
    {% include "includes/_footer.html" ignore missing %}
    </footer>
    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>

    <script src="{{url_for('static', filename='js/foundation.js')}}"></script>    
    <script src="{{url_for('static', filename='js/init.js')}}"></script>
    <script src="{{url_for('static', filename='js/quicksearch.js')}}"></script>
    {% block tail %}{% endblock %}
    
</body>
</html>

app/templates/macros.html
<!-- tariff_info() -->
{% macro tariff_info(tariff_obj) %}

{% if tariff_obj.is_link %}
<a href="{{url_for('ca.tariff_lookup', year=session.year, tariff=tariff_obj.tariff)}}" >
{% else %}
<a href="#" >
{% endif %}
    {% if tariff_obj.is_general_description %}
    <h6><em>{{tariff_obj.description}}</em></h6>
</a>
    {% else %}
    <div class="grid-x grid-margin-x align-center">
        
        {% if tariff_obj.tariff | length == 10 %}
        <div class="cell large-2 medium-3 tariff-link">
        {% else %}
        <div class="cell large-2 medium-3">
        {% endif %}
            {% if tariff_obj.is_heading %}
            <strong>{{tariff_obj.formatted_hs}}</strong>
            {% else %}
            {{tariff_obj.formatted_hs}}
            {% endif %}
        </div>    

        <div class="cell auto description">
            {{"- " * tariff_obj.dashes}} 
            {% if tariff_obj.is_heading %}
            <strong>{{tariff_obj.description}}</strong>
            {% else %}
            {{tariff_obj.description}}
            {% endif %}
        </div>
    </div>
</a>
    {% endif %}
{% endmacro %}


<!-- heading_accordion() -->
{% macro heading_accordion(tariff_dict, active=False) %}
<div class="grid-x grid-margin-x align-center">
    <div class="cell small-10 medium-9 large-8">
        {% for k_0, v_0 in tariff_dict.items() %}
        {% if v_0 is mapping %}
        <ul class="vertical menu accordion-menu" data-accordion-menu data-submenu-toggle="true">
            <li>{{tariff_info(v_0)}}
            {% for k_1, v_1 in v_0.items() %}
            {% if v_1 is mapping %}            
            <ul class="menu vertical nested {% if active == True %} is-active {% endif %}">
                <li>{{tariff_info(v_1)}}
                {% for k_2, v_2 in v_1.items() %}
                {% if v_2 is mapping %}                
                <ul class="menu vertical nested">
                    <li>{{tariff_info(v_2)}}
                    {% for k_3, v_3 in v_2.items() %}
                    {% if v_3 is mapping %}
                    <ul class="menu vertical nested">
                        <li>{{tariff_info(v_3)}}
                        {% for k_4, v_4 in v_3.items() %}
                        {% if v_4 is mapping %}
                            <li>{{tariff_info(v_4)}}</li>
                        {% endif %}
                        {% endfor %}
                        </li>                  
                    </ul>                    
                    {% endif %}
                    {% endfor %}
                    </li>                
                </ul>                
                {% endif %}
                {% endfor %}            
                </li>
            </ul>                        
            {% endif %}
            {% endfor %}        
            </li>
        </ul>        
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endmacro %}

{% macro notes(note_obj) %}

{% if note_obj.notes %}
<h3>Notes</h3>
<p>{{note_obj.notes }}</p>
{% endif %}
{% if note_obj.subheading_notes %}
<h3>Sub-heading Notes</h3>
<p>{{note_obj.subheading_notes}}</p>
{% endif %}
{% if note_obj.supplemental_notes %}
<h3>Supplemental Notes</h3>
<p>{{note_obj.supplemental_notes}}</p>
{% endif %}
{% if note_obj.statistical_notes %}
<h3>Statistical Notes</h3>
<p>{{note_obj.statistical_notes}}</p>
{% endif %}

{% endmacro %}

{% macro bookview(bookviewlist) %}
<!-- <div class="sections"> -->
    <table>
        <thead>
            <th>Tariff Item</th>
            <th>SS</th>
            <th>Description of Goods</th>
            <th>Unit of Measure</th>
            <th>MFN Tariff</th>
            <th>Applicable Preferential Tariffs</th>
        </thead>
        <tbody>
            {% for row in bookviewlist %}
            {#{% if row.tariff %}
            <section id="{{row.tariff}}{% if row.ss %}{{row.ss}}{% endif %}" data-magellan-target="{{row.tariff}}{% if row.ss %}{{row.ss}}{% endif %}"></section>
            {% endif %}#}
            <tr>
                {# FTA 
                <!-- <td width="200"><span data-tooltip class="top" tabindex="2" title="{{tt[fta]}}">{{fta | upper}}</span></td> -->
                #}
                <td width=60>{{row.tariff | format_hs}}</td>
                <td width=50><a href="{{url_for('ca.tariff_lookup', year=session.year, tariff=row.tariff + row.ss)}}"><u>{{row.ss}}</u></a></td>
                <td>{{"- " * row.dashes}}{{row.description}}</td>
                <td width=50>{{row.uom}}</td>
                <td width=100>{{row.mfn}}</td>
                <td width=200>
                    {% for k, v in row.apt.items()%}
                    {{v | join(', ') | upper()}}: {{k}}<br>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
<!-- </div> -->

{% endmacro %}

{% macro navbar() %}{% include "includes/_navbar.html" ignore missing %}{% endmacro %}